#Desafio - Fábrica de software (19/03/2026)- Machine Learning

##1. Atribuição das bibliotecas que serão utilizadas

In [34]:
import sys
import scipy
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from pandas.plotting import scatter_matrix
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

##2. declaração da tabela de dados que serão extraídos e polidos




In [12]:
df = pd.read_csv('/content/Video Games Sales (1980-2024) - Raw.csv')
df.head(20)

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,17-09-2013,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,18-11-2014,03-01-2018
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,28-10-2002,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,17-09-2013,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,06-11-2015,14-01-2018
5,/games/boxart/full_call-of-duty-modern-warfare...,Call of Duty: Modern Warfare 3,X360,Shooter,Activision,Infinity Ward,8.7,14.82,9.07,0.13,4.29,1.33,08-11-2011,NaN
6,/games/boxart/full_call-of-duty-black-ops_5Ame...,Call of Duty: Black Ops,X360,Shooter,Activision,Treyarch,8.8,14.74,9.76,0.11,3.73,1.14,09-11-2010,NaN
7,/games/boxart/full_4653215AmericaFrontccc.jpg,Red Dead Redemption 2,PS4,Action-Adventure,Rockstar Games,Rockstar Games,9.8,13.94,5.26,0.21,6.21,2.26,26-10-2018,02-11-2018
8,/games/boxart/full_1977964AmericaFrontccc.jpg,Call of Duty: Black Ops II,X360,Shooter,Activision,Treyarch,8.4,13.86,8.27,0.07,4.32,1.20,13-11-2012,07-04-2018
9,/games/boxart/full_4649679AmericaFrontccc.png,Call of Duty: Black Ops II,PS3,Shooter,Activision,Treyarch,8.0,13.80,4.99,0.65,5.88,2.28,13-11-2012,07-04-2018


In [16]:
df = df.drop(['img','title', 'publisher', 'developer', 'release_date', 'last_update'], axis=1, errors='ignore')
df['is_hit'] = df['total_sales'].fillna(0).astype(int)

In [17]:
#Removendo as linahs com valores vazios (garante menos instabilidade de dados)
df = df.dropna()

In [19]:
#Nesse sessão entramos na parte de polimento "avançado", servirá como pré processamento dos dados, transformando os dados relevantes todos na forma de números
le = LabelEncoder()
df['genre'] = le.fit_transform(df['genre'])
df['console'] = le.fit_transform(df['console'])

/tmp/ipykernel_315/3613738796.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genre'] = le.fit_transform(df['genre'])
/tmp/ipykernel_315/3613738796.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['console'] = le.fit_transform(df['console'])


In [22]:
#Separação dos dados (x representa nossos valores que serão usados como 'variáveis' enquanto o y será nosso target)
x = df.drop(['is_hit', 'total_sales', 'na_sales', 'jp_sales', 'pal_sales', 'other_sales'], axis=1)
y = df['is_hit']

In [24]:
#Divisão treino/teste
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

#Padronização
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

##3. Fazendo o treinamento do algoritmo


In [26]:
modelo = RandomForestClassifier(n_estimators=100, random_state=42)
modelo.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

##4. Testando o algoritmo


In [30]:
previsoes = modelo.predict(x_test)
acuracia = accuracy_score(y_test, previsoes)

print(f"Acurácia do modelo: {acuracia * 100:.2f}%")
print("\nMatriz de Confusão:")
print(confusion_matrix(y_test, previsoes))
print("\nRelatório de Classificação:")
print(classification_report(y_test, previsoes))

Acurácia do modelo: 50.41%

Matriz de Confusão:
[[112  18   5   3   2   0   1   0   0   0   1   0   0]
 [ 27   8   5   2   1   3   0   0   0   0   0   2   0]
 [  9   4   1   1   2   0   0   0   0   1   0   1   0]
 [  2   1   2   1   1   2   1   0   0   0   0   0   0]
 [  2   2   3   2   0   1   0   0   1   0   0   0   0]
 [  4   1   0   0   1   0   1   0   0   0   0   0   0]
 [  1   1   0   0   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   1   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]]

Relatório de Classificação:
              precision    recall  f1-score   support

           0       0.71      0.79      0.75       142
           1       0.22      0.17      0.19        48
           2       0.06      0.05      0.06 

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_

In [33]:

#Salvando a solução temos:
joblib.dump(modelo, 'modelo_de_vendas_dos_videogames.pkl')
print("\nModelo salvo com ducesso!")


Modelo salvo com ducesso!
